# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 016a31ca4f7a1a7afb06c566aa0da80edae74536450af9991a9b13724dcb7464f41dd96f65ab257669dc60f0a65232d4e666fe447069b0c91fe28efced19f58d

test:
  secret_key_base: dc024993e0e8d5a6bcebb6cbfda3bf929cdbe7ca0ee7d4d249131645aa47163a24a1259dfa7d9733136773a0c64082da3a123ec305f2be113b8cbd269084499c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
